// ============================================================================
//  Photo-to-ASCII  —  real-time ASCII video filter for OBS
//  Character ramp (dark -> light):  -.:*=+%#@
//
//  GENERATED by obs/build_ascii_shader.py — re-run that script to change the
//  characters. Load on any source via the obs-shaderfilter plugin
//  (Filters > + > User-defined shader > load this file).
//
//  Runs in one GPU pass with no CPU readback, so it keeps full frame-rate on
//  live video and layers cheaply with other sources. Controls appear as
//  sliders / dropdowns in the filter panel.
// ============================================================================

#define RAMP_LEN 10
#define GW 8
#define GH 8

// ── User controls ───────────────────────────────────────────────────────────

uniform float char_size<
    string label = "Character Size (px)";
    string widget_type = "slider";
    float minimum = 2.0;
    float maximum = 64.0;
    float step = 1.0;
> = 8.0;

uniform int char_count<
    string label = "Character Count";
    string widget_type = "slider";
    int minimum = 2;
    int maximum = RAMP_LEN;
    int step = 1;
> = 10;

uniform float contrast<
    string label = "Contrast";
    string widget_type = "slider";
    float minimum = 0.25;
    float maximum = 3.0;
    float step = 0.05;
> = 1.0;

uniform bool invert<
    string label = "Invert Brightness";
> = false;

uniform bool use_source_color<
    string label = "Use Source Colors";
> = true;

uniform float4 fg_color<
    string label = "Text Color";
    string widget_type = "color";
> = {1.0, 1.0, 1.0, 1.0};

uniform bool background_video<
    string label = "Show Source In Gaps";
> = false;

uniform float4 bg_color<
    string label = "Background Color";
    string widget_type = "color";
> = {0.0, 0.0, 0.0, 1.0};

uniform int blend_mode<
    string label = "Blend Mode";
    string widget_type = "select";
    int    option_0_value = 0;
    string option_0_label = "Normal";
    int    option_1_value = 1;
    string option_1_label = "Additive";
    int    option_2_value = 2;
    string option_2_label = "Screen";
    int    option_3_value = 3;
    string option_3_label = "Multiply";
    int    option_4_value = 4;
    string option_4_label = "Overlay";
    int    option_5_value = 5;
    string option_5_label = "Difference";
> = 0;

uniform float opacity<
    string label = "Opacity";
    string widget_type = "slider";
    float minimum = 0.0;
    float maximum = 1.0;
    float step = 0.01;
> = 1.0;

// ── Procedural glyph atlas (baked from your characters) ──────────────────────
// Each glyph is a GW×GH on/off bitmap packed into a float3 of 24-bit chunks.
// Bit index b = gy*GW + gx (row 0 = top, column 0 = left).

float3 glyph_bits(int gi)
{
    if (gi <= 0) return float3(0.0, 0.0, 0.0);
    if (gi == 1) return float3(0.0, 14336.0, 0.0);
    if (gi == 2) return float3(0.0, 1572864.0, 16.0);
    if (gi == 3) return float3(0.0, 1572888.0, 16.0);
    if (gi == 4) return float3(3936256.0, 24.0, 0.0);
    if (gi == 5) return float3(0.0, 32382.0, 0.0);
    if (gi == 6) return float3(0.0, 1605144.0, 0.0);
    if (gi == 7) return float3(1769472.0, 13660270.0, 0.0);
    if (gi == 8) return float3(7880704.0, 1474540.0, 0.0);
    return float3(12976128.0, 14387675.0, 6.0);  // gi == 9
}

// Returns 1.0 if glyph `gi` is lit at local cell position `p` (p in [0,1)).
float glyph_pixel(int gi, float2 p)
{
    int gx = clamp(int(floor(p.x * float(GW))), 0, GW - 1);
    int gy = clamp(int(floor(p.y * float(GH))), 0, GH - 1);
    int b = gy * GW + gx;
    float3 packed = glyph_bits(gi);
    float chunk = (b < 24) ? packed.x : ((b < 48) ? packed.y : packed.z);
    int bb = b - 24 * (b / 24);                 // b % 24
    return floor(fmod(chunk / exp2(float(bb)), 2.0));
}

// ── Blend ────────────────────────────────────────────────────────────────────
// Combine glyph ink `f` with whatever is behind it `b`.

float3 apply_blend(int mode, float3 b, float3 f)
{
    if (mode == 1) return saturate(b + f);                       // Additive
    if (mode == 2) return 1.0 - (1.0 - b) * (1.0 - f);           // Screen
    if (mode == 3) return b * f;                                 // Multiply
    if (mode == 4)                                               // Overlay
    {
        float3 lo = 2.0 * b * f;
        float3 hi = 1.0 - 2.0 * (1.0 - b) * (1.0 - f);
        return lerp(lo, hi, step(0.5, b));
    }
    if (mode == 5) return abs(b - f);                            // Difference
    return f;                                                    // Normal
}

// ── Main ─────────────────────────────────────────────────────────────────────

float4 mainImage(VertData v_in) : TARGET
{
    float4 src = image.Sample(textureSampler, v_in.uv);

    float cell = max(2.0, char_size);
    float2 grid = uv_size / cell;                 // virtual character grid

    // One luminance/colour sample per character cell (its centre) — this is the
    // "input resolution" the picture is read at.
    float2 cell_index  = floor(v_in.uv * grid);
    float2 cell_center = (cell_index + 0.5) / grid;
    float4 sampled     = image.Sample(textureSampler, cell_center);

    float lum = dot(sampled.rgb, float3(0.299, 0.587, 0.114));
    lum = saturate((lum - 0.5) * contrast + 0.5);
    if (invert) lum = 1.0 - lum;

    // Quantise brightness into `char_count` levels, then pick the glyph from the
    // baked ramp.
    int   n     = clamp(char_count, 2, RAMP_LEN);
    float level = min(floor(lum * float(n)), float(n - 1));      // 0 .. n-1
    float t     = level / float(n - 1);                          // 0 .. 1
    int   gi    = int(floor(t * float(RAMP_LEN - 1) + 0.5));     // 0 .. RAMP_LEN-1

    // Local position inside this cell, in [0,1).
    float2 local = frac(v_in.uv * grid);
    float  ink   = glyph_pixel(gi, local);

    // Compose: glyph ink over the chosen background.
    float3 behind_rgb = background_video ? src.rgb : bg_color.rgb;
    float  behind_a   = background_video ? src.a   : bg_color.a;

    float3 ink_color  = use_source_color ? sampled.rgb : fg_color.rgb;
    float3 lit_color  = apply_blend(blend_mode, behind_rgb, ink_color);

    float3 layer_rgb  = lerp(behind_rgb, lit_color, ink);
    float  layer_a    = max(behind_a, ink);

    // Master opacity mixes the whole result back toward the untouched source.
    float3 out_rgb = lerp(src.rgb, layer_rgb, opacity);
    float  out_a   = lerp(src.a,   layer_a,   opacity);

    return float4(out_rgb, out_a);
}
